### ISSUE TITLE
www.ivlivs.it/groceries is gone

### ISSUE THREAD

**Issue by dnschneid** [eevleevs/groceries#2]
www.ivlivs.it/groceries is gone, so the app 404s now.

If this was unintended, hopefully you can fix it!  It's a very handy watchapp on a (still) very handy platform.

If this was an intentional turn-down, would you be willing to share the server code so we can run our own instances?

**Comment by eevleevs** [comment]
Sorry, I changed server, and cannot maintain this app any longer.
Please find the server code in the server directory.

**Comment by dnschneid** [comment]
Thank you!
